## Dot Product Example Using Numpy and Pandas ( Nut-Butter-Sales)

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(0)
# Number of jars sold
sales_amounts  = np.random.randint(20,size = (5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [3]:
# Create weekly sales dataframe
weekly_sales = pd.DataFrame(sales_amounts ,
                           index = ["Mon" , "Tues" ,"Wed" , "Thur" , "Fri"] ,
                           columns = ["Almond Butter" , "Peanut Butter" , "Cashew Butter"])
weekly_salesekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [4]:
# Create Prices Array
prices =  np.array([10,8,12])
prices

array([10,  8, 12])

In [6]:
butter_prices = pd.DataFrame(prices.reshape(1,3) ,
                            index = ["Price"] ,
                            columns = ["Almond Butter" , "Peanut Butter" , "Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [7]:
total_sales = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [8]:
# Shapes are not aligned , so let's transpose
total_sales = prices.dot(sales_amounts.T)

In [9]:
total_sales

array([240, 138, 458, 232, 142])

In [10]:
# Create daily sales
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [11]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [12]:
butter_prices.shape , weekly_sales.shape

((1, 3), (5, 3))

In [14]:
weekly_sales.T.shape

(3, 5)

In [15]:
daily_sales =  butter_prices.dot(weekly_sales.T)

In [16]:
daily_sales

Mon  Tues  Wed  Thur  Fri
Price  240   138  458   232  142

In [17]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [18]:
weekly_sales["Total ($)"] =  daily_sales.T
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon              12             15              0        240
Tues              3              3              7        138
Wed               9             19             18        458
Thur              4              6             12        232
Fri               1              6              7        142